# Generated by Django 2.2 on 2019-05-09 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='issueDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='returDate',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
