# Generated by Django 2.2 on 2019-05-09 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190509_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='issueDate',
        ),
        migrations.RemoveField(
            model_name='issuebook',
            name='returDate',
        ),
    ]
